# Generated by Django 5.1.3 on 2024-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilo_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Iveskite markę (pvz. Ford )', max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Iveskite modelį (pvz. Focus )', max_length=100, verbose_name='Modelis')),
            ],
            options={
                'ordering': ['marke', 'modelis'],
            },
        ),
    ]
