# Generated by Django 5.1.3 on 2024-11-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_automobilis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Bus sutvarkyta')),
                ('status', models.CharField(blank=True, choices=[('a', 'Uzregistruota'), ('p', 'Eileje'), ('g', 'Tvarkoma'), ('r', 'Galima atsiimti')], default='a', help_text='Statusas', max_length=1)),
                ('automobilis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilis')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
