# Generated by Django 5.1.3 on 2024-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_uzsakymas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Iveskite paslaugos pavadinima (pvz.Tepalu keitimas)', max_length=100, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(help_text='Iveskite kaina paslaugos(pvz: 199)', max_length=250, verbose_name='Kaina')),
            ],
        ),
    ]
