# Generated by Django 5.1.3 on 2024-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_paslauga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paslauga',
            name='kaina',
            field=models.IntegerField(help_text='Iveskite kaina paslaugos(pvz: 199)', verbose_name='Kaina'),
        ),
    ]
