# Generated by Django 5.1.3 on 2024-11-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_paslauga_kaina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(help_text='Iveskite kieki', max_length=250, verbose_name='Kiekis')),
                ('paslauga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.paslauga')),
                ('uzsakymo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.uzsakymas')),
            ],
        ),
    ]
