# Generated by Django 5.1.3 on 2024-11-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_uzsakymo_eilute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Iveskite Valstybini nr.(pvz AAA000)', max_length=15, verbose_name='Valstybinis_NR')),
                ('vin_kodas', models.CharField(help_text='Iveskite VIN (pvz.3C6UR5CJXEG146621)', max_length=17, verbose_name='VIN_Kodas')),
                ('klientas', models.CharField(help_text='Vardas Pavarde pvz(Juozas Juozaitis)', max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilo_modelis')),
            ],
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobili'),
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
    ]
