# Generated by Django 5.1.3 on 2024-11-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_automobili_alter_uzsakymas_automobilis_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automobili',
            new_name='Automobilis',
        ),
    ]
