# Generated by Django 5.1.3 on 2024-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_rename_automobili_automobilis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilo_modelis',
            options={},
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('uzregistruotas', 'Uzregistruota'), ('eileje', 'Eileje'), ('tvarkomas', 'Tvarkoma'), ('Galima atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20),
        ),
    ]
