# Generated by Django 5.1.3 on 2024-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_alter_automobilo_modelis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilo_modelis',
            options={'verbose_name': 'Automobilo modelis', 'verbose_name_plural': 'Automobilio modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'ordering': ['data'], 'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymo_eilute',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutės'},
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='klientas',
            field=models.CharField(help_text='Vardas Pavardė pvz. (Juozas Juozaitis)', max_length=100, verbose_name='Klientas'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(help_text='Įveskite valstybinį nr. (pvz AAA000)', max_length=15, verbose_name='Valstybinis_NR'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='vin_kodas',
            field=models.CharField(help_text='Įveskite VIN (pvz. 3C6UR5CJXEG146621)', max_length=17, verbose_name='VIN_Kodas'),
        ),
        migrations.AlterField(
            model_name='automobilo_modelis',
            name='marke',
            field=models.CharField(help_text='Įveskite markę (pvz. Ford)', max_length=100, verbose_name='Markė'),
        ),
        migrations.AlterField(
            model_name='automobilo_modelis',
            name='modelis',
            field=models.CharField(help_text='Įveskite modelį (pvz. Focus)', max_length=100, verbose_name='Modelis'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='kaina',
            field=models.IntegerField(help_text='Įveskite paslaugos kainą (pvz. 199)', verbose_name='Kaina'),
        ),
        migrations.AlterField(
            model_name='paslauga',
            name='pavadinimas',
            field=models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz. Tepalų keitimas)', max_length=100, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('Uzregistruotas', 'Uzregistruota'), ('Eileje', 'Eileje'), ('Tvarkomas', 'Tvarkoma'), ('Galima atsiimti', 'Galima atsiimti')], default='uzregistruotas', help_text='Statusas', max_length=20),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kiekis',
            field=models.CharField(help_text='Įveskite kiekį', max_length=250, verbose_name='Kiekis'),
        ),
    ]
